### ISSUE TITLE
Town NPC quest dialog stuck at 'The Butcher' even after killing him

### ISSUE THREAD

**Issue by diablobug** [d07RiV/diabloweb#104]
Newer and later quests after 'The Butcher' did appear and complete as usual on the Quest Log. The relevant town NPCs also did trigger later quests normally (added to the Quest Log).

Details: I skipped 'The Butcher' quest (too hard!) and completed later quests first before going back to it.

Quest pack received so far: Butcher - Leoric - Magic Rock - Gharbad the Weak - Chamber of Bone

Tech details: Windows PC, Chromium browser. Used the online tool provided to compress DIABDAT.MPQ to half the original size, to around 250Mb.

![quest dialog](https://user-images.githubusercontent.com/56663518/66973835-b22f9180-f0cb-11e9-8568-6f9172fbe561.png)

**Comment by AJenbo** [comment]
This has already been fixed upstream and there is already an issue about it I'm diabloweb. But the project isn't being maintained at the moment.
