### ISSUE TITLE
Npq file not working

### ISSUE THREAD

**Issue by Lucrowebb** [d07RiV/diabloweb#108]
![Screenshot_20191103-232026](https://user-images.githubusercontent.com/57344016/68143125-a292b400-fee5-11e9-832f-18a4b93158cb.png)
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Retail)

**Error message:**
    
    NotReadableError: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.

**User agent:**

    Mozilla/5.0 (Linux; Android 8.0.0; moto e5 plus) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.62 Mobile Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
Duplicate

**Comment by AJenbo** [comment]
There is now a version for Android which should provide a much better experience: https://play.google.com/store/apps/details?id=org.diasurgical.devilutionx
