### ISSUE TITLE
Microsoft Edge - No Audio

### ISSUE THREAD

**Issue by Damage242** [d07RiV/diabloweb#111]
![example2](https://user-images.githubusercontent.com/57753155/68850471-ff535300-06cb-11ea-9d56-155b4f015e2f.PNG)
Bought and downloaded the GoG release of Diablo.
Have pulled the MPQ file into the webbrowser, and it works smoothly. But there is no audio! And I can't figure out why... Not even the tab is showing any sign of the tab playing any audio, which makes me suspicious of what the error could be.
It works well in Chrome, but the whole point of me buying this was to be able to play it on work computers, which only have Edge.

**Comment by AJenbo** [comment]
MS has made Edge a Chrome-based browser at this point, so it should work now.
