### ISSUE TITLE
I can't leave first dungeon

### ISSUE THREAD

**Issue by TSGG1676** [d07RiV/diabloweb#114]
**Description:**
I went to leave for town and I got this error message. I loaded up the full version, DIABDAT.MPQ. I'm pretty sure there isn't any problems with my file.

**App version:**
DiabloWeb 1.0.13 (Retail)

**Error message:**
    
    Unable to open save file

**Comment by AJenbo** [comment]
Duplicate https://github.com/d07RiV/diabloweb/issues/98
