### ISSUE TITLE
I can't play on mobile

### ISSUE THREAD

**Issue by windows9x95** [d07RiV/diabloweb#118]
When I load my DIABDAT.MPQ on my phone I got an error
![IMG_20200117_193059](https://user-images.githubusercontent.com/59638234/72636705-f139e100-395f-11ea-9f3c-b31d8f2a5a81.jpg)
Can you help me please

**Comment by AJenbo** [comment]
What phone, what browser, what file permissions?

**Comment by windows9x95** [comment]
I'm on a Xiaomi Redmi 8a, on opera mobile, I tried with chrome, same error. for the file permission, I don't know why, I copied the file from my pc

**Comment by AJenbo** [comment]
Definatly check file permissins and maybe the md5. Also I would recommend trying the native Android builds instead of the browser based one.
https://github.com/diasurgical/devilutionX

**Comment by windows9x95** [comment]
I will try thanks

**Comment by AJenbo** [comment]
The Android version is now available from the play store: https://play.google.com/store/apps/details?id=org.diasurgical.devilutionx
