### ISSUE TITLE
Diablo bug?

### ISSUE THREAD

**Issue by Phazed1** [d07RiV/diabloweb#120]
**Description:**
I was clearing the 1st dungeon and finished floor 2. I traveled to floor one with no issues, but when I went to head into town my game file crashed and could not load up. ^^

**App version:**
DiabloWeb 1.0.13 (Shareware)

**Error message:**
    
    Unable to open save file

**Comment by sskras** [comment]
Did it happen while in a Single player mode?

**Comment by sskras** [comment]
Did it happen in a Single player mode?

**Comment by AJenbo** [comment]
This issue was fixed already, pelase run the latest version (1.0.39) at https://d07riv.github.io/diabloweb/
