### ISSUE TITLE
dsa

### ISSUE THREAD

**Issue by 0tnc** [d07RiV/diabloweb#127]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.13 (Shareware)

**Error message:**
    
    TypeError: Failed to fetch

**Comment by AJenbo** [comment]
[Please describe what you were doing before the error occurred]

**Comment by AJenbo** [comment]
Closed because it's not using the latest version (1.0.39): https://d07riv.github.io/diabloweb/
