### ISSUE TITLE
diabdat.mpq

### ISSUE THREAD

**Issue by annalasek** [d07RiV/diabloweb#132]
**Description:**
Trying to start regular version of Diablo with diabdat.mpq

**App version:**
DiabloWeb 1.0.19 (Retail)

**Error message:**
    
    Main program archive: diabdat.mpq

**User agent:**

    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
Please use the latest version, where are you playing the old one from?

https://d07riv.github.io/diabloweb/
