### ISSUE TITLE
Partida Diablo 1 ¿?

### ISSUE THREAD

**Issue by GranKiwi** [d07RiV/diabloweb#134]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Shareware)

**Error message:**
    
    ReferenceError: Can't find variable: WebAssembly
    https://d07riv.github.io/diabloweb/b6959098d798174bd69f.worker.js:1:38591
    https://d07riv.github.io/diabloweb/b6959098d798174bd69f.worker.js:1:78234
        at obj (../node_modules/regenerator-runtime/runtime.js:45:0)
    https://d07riv.github.io/diabloweb/b6959098d798174bd69f.worker.js:1:58095
        at arg (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:0)
        at gen (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:0)
    promiseReactionJob@[native code]

**User agent:**

    Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
[Please describe what you were doing before the error occurred]
