### ISSUE TITLE
fuck

### ISSUE THREAD

**Issue by lenbarad22** [d07RiV/diabloweb#136]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.13 (Shareware)

**Error message:**
    
    e/</</<@https://emupedia.net/emupedia-game-diablo1/static/js/main.26aae697.chunk.js:193:15

**Comment by AJenbo** [comment]
Your playing an old version on an unofficial page, use the latest instead: https://d07riv.github.io/diabloweb/
