### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by Alancitoh** [d07RiV/diabloweb#145]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Retail)

**Error message:**
    
    NotReadableError: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.

**User agent:**

    Mozilla/5.0 (Linux; Android 7.0; Moto C Plus) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.83 Mobile Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
[Please describe what you were doing before the error occurred]

**Comment by AJenbo** [comment]
There is now a version for Android which should provide a much better experience: https://play.google.com/store/apps/details?id=org.diasurgical.devilutionx
