### ISSUE TITLE
Error: Connection Timed Out / Game not found

### ISSUE THREAD

**Issue by clydevins** [d07RiV/diabloweb#146]
Windows 10 machine using both Google Chrome and Firefox.

When trying to create a Multiplayer Game via WebSocket (Server) the following message presents: "Connection Timed Out".   This had worked successfully for months.  Singleplayer works fine.

Tried refreshing.  Clearing browser cache.  Restarting browsers.  Computer reboot.  None of these actions have resolved the issue.  

Please advise.  Thanks tons.

**Comment by AJenbo** [comment]
Duplicate https://github.com/d07RiV/diabloweb/issues/99

Use DevilutionX for multiplayer

**Comment by clydevins** [comment]
> Duplicate #99
> 
> Use DevilutionX for multiplayer

Please provide more information.  The 3 folks that play in our group have not had any issues in months.  Why now ?  What's the difference/cause for this error.  If DevilutionX is indeed the solution please provide working link.  Thanks

**Comment by AJenbo** [comment]
DiabloWeb is not maintained, it's multiplayer was mostly proof of consept.

https://github.com/diasurgical/devilutionX
