### ISSUE TITLE
Connection timed out.  

### ISSUE THREAD

**Issue by clydevins** [d07RiV/diabloweb#147]
Somehow this issue got closed without explanation.

Multiple different players and different browsers getting error message Connection Timed Out.

Please advise.  Thank you.

EDIT

This is the link we have been using:  https://d07riv.github.io/diabloweb/

Trying to play Classic Diablo (I).

**Comment by AJenbo** [comment]
You got an explanation, it's a duplicate. Opening another isn't going to change that.

Duplicate #99

**Comment by clydevins** [comment]
Do you happen to know why ?

Despite now being supported it was working for months and as recent as two days ago.
It was nice to be able to play within a browser window.

**Comment by AJenbo** [comment]
The server could have been back up for unrelated reasons
