### ISSUE TITLE
Linux Chrome - Black screen

### ISSUE THREAD

**Issue by ainiml** [d07RiV/diabloweb#15]
**Description:**
Linux `Chrome Version 77.0.3860.5 (Official Build) dev (64-bit)` shows a black screen

Music plays, takes keyboard+mouse input, but no display

**App version:**
DiabloWeb 1.0.3 (Shareware)

**Error message:**
n/a

**Comment by d07RiV** [comment]
Do you get a black screen as you start the game?

**Comment by ainiml** [comment]
Black screen as soon as you load your Diablo game file

**Comment by sskras** [comment]
I get the same effect on my Chromebook:

![image](https://user-images.githubusercontent.com/7887758/62417459-7bafb200-b658-11e9-9584-76a07bf1f990.png)

**Comment by tomekk01** [comment]
I also run Linux (Manjaro) and game is loading just fine within Chrome. I use the file from GOG distribution of D1. "Version 75.0.3770.142 (Official Build) (64-bit)"

**Comment by d07RiV** [comment]
I tried in Ubuntu VM and it works fine. You're saying you can hear the sounds from mouse/keyboard navigating in the menu, but everything is black? That's really weird :|

**Comment by sskras** [comment]
@d07RiV have you tested namely Chrome, not Chromium by a chance?

I recorded a video: https://webm.red/7pQM

The intro screen renders OK with buttons `[ Select MPQ ]` and `[ Play Shareware ]` rendered.  If I press the latter, screen goes black.  

Then I press `Enter`, and the intro music starts playing.
Then I press `Down` two times in a row, still nothing gets rendered.
Then I press `Up` two times in a row and then `Enter` to get into Single Player invisibly, still no view.
Then I press `Esc` and the `Up` two times in a row.

I get into the credits, and now they are drawn, albeit very blurry (buggy).

Then I right-click on the tab's side (~0:47s), presumably return to the main menu. 
The scrolling stops being rendered and stays on screen.

I try right-clicking once more (as I want to get to the Chrome's Inspector), but instead activate some unknown action (the menu pressing sound occurs).

I try moving the cursor around the tab and right clicking for a while. After getting lost I press `Esc`, hear the pressing sound again, and the game quits.

**Comment by d07RiV** [comment]
Oh wow so it's definitely working, just not drawing anything. I'll try again and see if I can reproduce it.

**Comment by OrangBuangan** [comment]
@ainiml do you also see this with Firefox?

**Comment by knickum** [comment]
FWIW, works fine on my Acer Chromebook, either running in ChromeOS or Chromium via Crouton (XFCE)

**Comment by sskras** [comment]
Now it's drawing on my Lenovo Chromebook N22 too. I am not sure which exact commit fixed it.

**Comment by d07RiV** [comment]
Going to close if there are no further updates on this.
