### ISSUE TITLE
how to use spells? (android, web)

### ISSUE THREAD

**Issue by hdgayua** [d07RiV/diabloweb#160]
I'm most likely stupid but how do I use spells?
I've never played d1 in first case so havnt tries it on computer eighter but anyhow I managed to bind switching spells to diffrent buttons so I can quickly change between them, but when pressing the spell It just shows all my spells both with short and long press. cant use them. It says I'm supposed to right click but how do I simulate right click beside long press? Left side buttons only left me hold shift or right click..

Really cant figure this one out so any help would be appriciated.

**Comment by AJenbo** [comment]
Duplicate https://github.com/d07RiV/diabloweb/issues/150

**Comment by AJenbo** [comment]
There is now a version for Android which has button for casting spells: https://play.google.com/store/apps/details?id=org.diasurgical.devilutionx
