### ISSUE TITLE
Diablo mobile

### ISSUE THREAD

**Issue by SLFul** [d07RiV/diabloweb#161]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Shareware)

**Error message:**
    
    TypeError: Cannot read property 'Memory' of undefined
        at https://d07riv.github.io/diabloweb/b6959098d798174bd69f.worker.js:1:38591
        at https://d07riv.github.io/diabloweb/b6959098d798174bd69f.worker.js:1:78234
        at call (../node_modules/regenerator-runtime/runtime.js:45:0)
        at tryCatch (../node_modules/regenerator-runtime/runtime.js:264:0)
        at _invoke (../node_modules/regenerator-runtime/runtime.js:98:0)
        at arg (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:0)
        at asyncGeneratorStep (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:0)

**User agent:**

    Mozilla/5.0 (Linux; Android 4.2.2; ME173X Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.124 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
[Please describe what you were doing before the error occurred]

**Comment by SLFul** [comment]
hm,nothing.I just clicked on the link,downloaded it, and at the end it said "the following has occurred cannot read property "memory""

**Comment by AJenbo** [comment]
It's now a download. Maybe you are out of memory. This isn't optimized for low-end devices.

**Comment by AJenbo** [comment]
There is now a version for Android which should provide a much better experience: https://play.google.com/store/apps/details?id=org.diasurgical.devilutionx
