### ISSUE TITLE
Help! Lost Character!!

### ISSUE THREAD

**Issue by jneutro** [d07RiV/diabloweb#164]
Ah, I am distraught! I've been playing this on my android for the last month, and it's been great. I had a pretty great warrior, but then something happened on my phone, and my character is no longer there. There wasn't even a specific incident that seems to have caused this! This also means I have no error report, so I'm hoping someone can help me with some creative problem solving.

How are things like characters stored in this magical rebirth of Diablo 1? I notice that when I open my mpq on my computer, it will save a character no prob, even when I open it up multiple times. However, as soon as I open the exact same file in incognito, the character is nowhere to be found. 

Please, help find my character, and bring him back to life!

**Comment by AJenbo** [comment]
They are saved in the browser local storage, if you clear it you loos them.

**Comment by jneutro** [comment]
So is there no way to back up characters? And is there any chance of retrieving this lost character?

**Comment by AJenbo** [comment]
If they where wiped from your browsers memory there is no way to get them back, some browsers may clear such data automatically based on available space, there are also a lot of disk cleaner tools that does this. So best to back such data up if your local storage is periodically emptied.

**Comment by jneutro** [comment]
How do you back up chrome local storage files?

**Comment by AJenbo** [comment]
Idk, I don't use Chrome. But I was refering to the "Manage Saves" option that you get before starting the game.

**Comment by AJenbo** [comment]
There is now a version for Android which should provide a much better experience, save games are instead on the internal storage and can be copied just like any other file, and won't get cleared automatically: https://play.google.com/store/apps/details?id=org.diasurgical.devilutionx
