### ISSUE TITLE
Chrome 88 failes on postMessage

### ISSUE THREAD

**Issue by fabiofauze** [d07RiV/diabloweb#172]
**Description:**
After pressing "Play Shareware" the game fails to launch once the loading process is compleat.

**App version:**
DiabloWeb 1.0.39 (Shareware)

**Error message:**
    
    DataCloneError: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': ArrayBuffer is not detachable and could not be cloned.
        at buffer (api/game.worker.js:278:34)
        at self (api/DiabloSpawn.jscc:1644:39)
        at __ZN14websocket_impl4sendERK6packet (<anonymous>:wasm-function[1568]:0xe2df6)
        at dynCall_vii (<anonymous>:wasm-function[2086]:0xfe936)
        at a.dynCall_vii (api/DiabloSpawn.jscc:2698:0)
        at sp (api/DiabloSpawn.jscc:2263:0)
        at __ZN3net16websocket_clientC2Ev (<anonymous>:wasm-function[1600]:0xe4bb0)
        at dynCall_vi (<anonymous>:wasm-function[2085]:0xfe922)
        at a.dynCall_vi (api/DiabloSpawn.jscc:2694:0)
        at sp (api/DiabloSpawn.jscc:2252:0)

**User agent:**

    Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36

**Comment by AJenbo** [comment]
Can you try another browser like Firefox or Edge?

**Comment by DrJones1973** [comment]
I tried Edge - nothing, empty site after I selected MPQ, just flashed "Loading..."

**Comment by AJenbo** [comment]
should work in Firefox. If you can run a local application an alternative is also using https://github.com/diasurgical/devilutionX/releases

**Comment by DrJones1973** [comment]
> should work in Firefox. If you can run a local application an alternative is also using https://github.com/diasurgical/devilutionX/releases
Thanks! It works!

**Comment by NewfieWannabe** [comment]
But for those of us who don't like / use Firefox, what are the options ?

**Comment by AJenbo** [comment]
- Complain to Google that they broke Chrome
- Find a workaround
- Use DevilutionX
- Wait a few months

**Comment by d07RiV** [comment]
Seems disabling websocket (which doesn't work anyway) fixes the issue. No idea why it's happening, I can't even debug it because tab crashes if I try to set a breakpoint.

Pushed a build without it, seems to work now.

**Comment by AJenbo** [comment]
@trondkla repoted that deleting the cache allows the game to start.

**Comment by AJenbo** [comment]
If you are still experiencing this issue then please let us know what site you are running it from and what browser and possible browser extensions you are using.

**Comment by AJenbo** [comment]
To anyone still experiencing this please make sure you are running the game from https://d07riv.github.io/diabloweb/ and not some other site with an older copy.

**Comment by sskras** [comment]
@AJenbo commented [on Feb 19, 2021](#issuecomment-782242058):

> * Complain to Google that they broke Chrome
> * Find a workaround
  ...
> * Wait a few months

Do you see specifically what was broken in Chrome?
It would be nice to describe the issue to the Google dev in clear way (so they don't have to guess).

**Comment by AJenbo** [comment]
@sskras this issue was already resolved.

**Comment by sskras** [comment]
Thanks for the news!
Did you know the release/version of the fix by a chance?

**Comment by AJenbo** [comment]
It unfortunately didn't a version, but it was sometime before [Jul 11, 2021](https://github.com/d07RiV/diabloweb/issues/172#event-5004530782)

Any particular reason?

**Comment by sskras** [comment]
Just in case I will be forced to run older Chrome version.  Eg. getting a spare PC with unmaintained OS.
Or maybe running on [@reactos](https://github.com/reactos/reactos) which misses [support very new versions of browsers](https://twitter.com/reactos/status/1429805634409705473) yet.
