### ISSUE TITLE
404 Error after clicking Play Shareware

### ISSUE THREAD

**Issue by refractionpcsx2** [d07RiV/diabloweb#2]
Not sure what's going on (or if this is even the right place to post it) but on https://d07riv.github.io/diabloweb/ once you click on Play Shareware you get the error

Request failed with status code 404

Hope you can fix it soon, looking forward to this! :)

**Comment by francoispeyret** [comment]
https://d07riv.github.io/spawn.mpq is required but it was missing on this url

**Comment by refractionpcsx2** [comment]
Thanks @francoispeyret I was just about to update my issue with that lol

**Comment by jlubeck** [comment]
Seeing the same issue

**Comment by MitchellSingleton** [comment]
it appears that in this file:
main.b25d6053.chunk.js

there is one instance of the path that is absolute (to fix I removed the starting slash):
,D.a.request({url:"/spawn.mpq",
to this:
,D.a.request({url:"spawn.mpq",

**Comment by levinotik** [comment]
Also getting a 404 :(

**Comment by jridgewell** [comment]
Download https://d07riv.github.io/diabloweb/spawn.mpq, use "Select MPQ", then chose the downloaded version.

**Comment by d07RiV** [comment]
Fixing.

**Comment by superhawk610** [comment]
Looks like the most recent commit to https://d07riv.github.io/diabloweb/spawn.mpq removed `spawn.mpq`..?

![Screen Shot 2019-08-01 at 4 20 05 PM](https://user-images.githubusercontent.com/18172185/62324831-4ea4a900-b478-11e9-8152-76e19338a177.png)

https://github.com/d07RiV/diabloweb/commit/e03d97ad3916fb54260e60a25c4fb7e2157b8a6b

**Comment by francoispeyret** [comment]
@d07RiV not fixed

why not include the file's link directly in interface ? cc: @superhawk610

**Comment by d07RiV** [comment]
Removed it by accident, it's back now.

There is no need to link the file since the site can download it on its own, as long as I don't mess up.

**Comment by refractionpcsx2** [comment]
Haven't tried it yet, but thanks very much for fixing it quickly :)
