### ISSUE TITLE
Crash upon entering dungeon level two

### ISSUE THREAD

**Issue by jooosh** [d07RiV/diabloweb#20]
**Description:**
Entering dungeon level 2 in first dungeon and received this generic string error.  Using latest version of Chrome on an iMac.

**App version:**
DiabloWeb 1.0.11 (Shareware)

**Error message:**
    
    String

**Comment by danilodorgam** [comment]
I have the same error. Using latest version of Chrome on an Linux Mint.

**Comment by Serthys** [comment]
Same error with Chrome 75.0.3770.142 on Windows 10 .

**Comment by ArturM94** [comment]
Same. Opera 62.0.3331.99, Windows 10 64-bit.

**Comment by JEZHDK** [comment]
Same error  using chome on linux mint.

**Comment by d07RiV** [comment]
It was related to Butcher quest (which is not available in shareware), should be fixed now.
