### ISSUE TITLE
Unable to start shareware game

### ISSUE THREAD

**Issue by bug-re-port-er** [d07RiV/diabloweb#30]
**Description:**
Click on 'Play Shareware'.

**App version:**
DiabloWeb 1.0.11 (Shareware)

**Error message:**
    
    e/</</<@https://d07riv.github.io/diabloweb/static/js/main.080958d7.chunk.js:1:4278

Also 

    e.exports@https://d07riv.github.io/diabloweb/fc05444e24a262ff2a58.worker.js:1:11147
    e.exports/</_.onerror@https://d07riv.github.io/diabloweb/fc05444e24a262ff2a58.worker.js:1:10190

**Comment by d07RiV** [comment]
1. Does it happen every time?
2. Do the loading bars complete before it gives the error?

**Comment by AppleSeed2010** [comment]
Hi,
Same pb here.
The loading bar complete and then...
F5 or CTRL+F5 same pb.

(I'm under arch linux with firefox)

**Comment by bug-re-port-er** [comment]
1. yes
2. there are no loading bars, just errors.

**Comment by AJenbo** [comment]
@bug-re-port-er @AppleSeed2010 could you please test if this still happens on version 1.0.39, if so then please make a comment here and we will reopen the issue.

**Comment by AppleSeed2010** [comment]
Bug resolved for me :)
