### ISSUE TITLE
Gg

### ISSUE THREAD

**Issue by robwrtus** [d07RiV/diabloweb#324]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Retail)

**Error message:**
    
    NotReadableError: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.

**User agent:**

    Mozilla/5.0 (Linux; U; Android 6.0.1; pt-BR; SM-J500M Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 UCBrowser/13.3.8.1305 Mobile Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
[Please describe what you were doing before the error occurred]

**Comment by AJenbo** [comment]
There is now a version for Android which should provide a much better experience: https://play.google.com/store/apps/details?id=org.diasurgical.devilutionx
