### ISSUE TITLE
Real fans pay most?

### ISSUE THREAD

**Issue by klear6** [d07RiV/diabloweb#332]
It kinda sucks that I need proof of purchase from GOG. I played for and owned the original disc(s). I played it a lot and went thru a couple. Technically my dad bought them. But you know what i mean. Its not at all specific to or a jab at your app. GOG code makes perfect sense, but is there any alternative way for proof? just find it frustrating and ironic that i love this game a lot and have to buy it again again. a lot of people already own this from elsewhere...or I'm confused . But other than my foot-stomping , I really like what you've done here. Runs smooth in a floating browser on a tab s6. I'm super impressed. *clap* yay

**Comment by AJenbo** [comment]
There is no such requirement. The game requires the game data to run or you will be looking at a blank screen with no sound which isn't much fun. If you have the original CD simply use the DIABDAT.MPQ from there to play.

**Comment by klear6** [comment]
My bad - thanks for clearing that up. I do, indeed have the original so I guess I'm all set. Awesome project.
