### ISSUE TITLE
Game crashed when going up to town

### ISSUE THREAD

**Issue by tomekk01** [d07RiV/diabloweb#39]
**Description:**
[Please describe what you were doing before the error occurred]
I just killed the Butcher, went down for 3rd level, killed a few monsters and wanted to get back to the Town. I just moved way up and instead of loading the Town game crashed.

**App version:**
DiabloWeb 1.0.14 (Retail)

**Error message:**
    
    Unable to open save file

**User agent:**

    Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by tomekk01** [comment]
I have loaded the sv file (from before killing the Butcher) and I already can't go back to the Town. Not sure if worth trying to find Town Portal and use this instead could work as work around? I have also uploaded the sv file here. Hope this helps.

[single_0.zip](https://github.com/d07RiV/diabloweb/files/3464299/single_0.zip)

?

**Comment by d07RiV** [comment]
The town file is corrupted somehow, I'm seeing a lot of these but I've never been able to reproduce it myself.

Could you try to remember what you were doing in this save? Like going back to menu at some points, switching characters etc? Or maybe reproduce it if possible.

**Comment by d07RiV** [comment]
Going to merge all similar issues into that one -> #14

**Comment by tomekk01** [comment]
> The town file is corrupted somehow, I'm seeing a lot of these but I've never been able to reproduce it myself.
> 
> Could you try to remember what you were doing in this save? Like going back to menu at some points, switching characters etc? Or maybe reproduce it if possible.

Thanks for answering. I just did Save before going for the Butcher - the save was taken near his room already in the Dungeon on the second level. After I was able to get him (first attempt) I went one level deeper but because my inventory was almost full I went back those 2 levels and when trying to use the stairs to the surface, the game crashed with the error regarding save - you mentioned that probably wrong error message was displayed even as I was not trying to load the save. I'm not sure what do you mean by reproducing? With new character repeating all 2 levels, making save killing butcher, going down one level and then up to the surface? This was my first character.

**Comment by ggarfer** [comment]
Happened the same to me. Can't go back to town.
