### ISSUE TITLE
Cannot input text to get past New Single Player Hero

### ISSUE THREAD

**Issue by superhawk610** [d07RiV/diabloweb#4]
I cannot input text to create a new character, not sure if there's just something I'm missing?

## System

```
OS: macOS Mojave 10.14.5 18F132 x86_64
Host: MacBookPro12,1
Kernel: 18.6.0
Packages: 48 (brew)
Shell: zsh 5.3
Resolution: 3440x1440
CPU: Intel i5-5287U (4) @ 2.90GHz
GPU: Intel Iris Graphics 6100
Memory: 9654MiB / 16384MiB
```

## Screenshot
![Screen Shot 2019-08-01 at 4 27 01 PM](https://user-images.githubusercontent.com/18172185/62325249-413bee80-b479-11e9-99d4-6355d5b41bbe.png)

**Comment by nikopp** [comment]
I have the same problem. Win10, tried Firefox, Chrome and Edge.
I can use the keyboard to select Single Player but on the screen shown above, the keys I press seem to have no effect.

**Comment by naaada06** [comment]
same problem here
OS: Ubuntu 18.04.02
Browsers: Firefox and Chromium

**Comment by Greenzaker** [comment]
Same here
Win7 Firefox

**Comment by d07RiV** [comment]
Oops, #3 broke this, deploying fix.

**Comment by naaada06** [comment]
> Oops, #3 broke this, deploying fix. On a side note, it _should_ work on apple phones now as well.
> 
> Note that the page won't update until you refresh it _and then_ close and reopen, due to how caching works.

working fine now!
thanks!

**Comment by superhawk610** [comment]
That got it, thanks!
