### ISSUE TITLE
Characters start with wrong attributes

### ISSUE THREAD

**Issue by SalusaSecondus** [d07RiV/diabloweb#41]
I have the full game (dug up my old CD) and whenever I create a new character none of the attributes look correct upon creation.

I'm on Windows 10 and have this problem both in Firefox 68.0.1 and Chrome 75.0.3770.142

![rogue](https://user-images.githubusercontent.com/829871/62419402-07fbae00-b634-11e9-8a3e-01e3ee0e543e.png)
![sorcerer](https://user-images.githubusercontent.com/829871/62419403-07fbae00-b634-11e9-94b6-372e5edab1e9.png)
![warrior](https://user-images.githubusercontent.com/829871/62419404-07fbae00-b634-11e9-90d6-6526140ee119.png)

**Comment by d07RiV** [comment]
Oops I was testing something and forgot to undo it :|
