### ISSUE TITLE
Diablo

### ISSUE THREAD

**Issue by ZarkTye** [d07RiV/diabloweb#416]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Retail)

**Error message:**
    
    NotReadableError: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.

**User agent:**

    Mozilla/5.0 (Linux; Android 8.1.0; Moto G (5S) Plus) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
[Please describe what you were doing before the error occurred]

**Comment by ZarkTye** [comment]
I went to select the DIABDAT.MPQ file and gave this error

Em seg, 14 de jun de 2021 21:48, Anders Jenbo ***@***.***>
escreveu:

**Comment by AJenbo** [comment]
Make sure you have read premission to the file, also list you browser platform and url where you are trying this.

**Comment by ZarkTye** [comment]
Thanks, I'll check it out.

Em seg, 14 de jun de 2021 21:54, Anders Jenbo ***@***.***>
escreveu:

**Comment by ZarkTye** [comment]
which browser can i use on android


Em seg, 14 de jun de 2021 21:54, Anders Jenbo ***@***.***>
escreveu:

**Comment by AJenbo** [comment]
Firefox, but we are working on a native Android version atm so that will probably be a better solution.,

**Comment by ZarkTye** [comment]
ok I will test


Em seg, 14 de jun de 2021 22:03, Anders Jenbo ***@***.***>
escreveu:

**Comment by ZarkTye** [comment]
in firefox the screen went black


Em seg, 14 de jun de 2021 21:48, Anders Jenbo ***@***.***>
escreveu:

**Comment by AJenbo** [comment]
https://46096-143324737-gh.circle-artifacts.com/0/devilutionx-debug.apk

**Comment by ZarkTye** [comment]
And now what do I do


Em seg, 14 de jun de 2021 22:18, Anders Jenbo ***@***.***>
escreveu:

**Comment by ZarkTye** [comment]
Already installed


Em seg, 14 de jun de 2021 22:21, Um Gamer Novo ***@***.***>
escreveu:

**Comment by AJenbo** [comment]
Look at Github for instructions, but I would recommend waiting for the proper release.

**Comment by ZarkTye** [comment]
Ok Thanks Man

Em seg, 14 de jun de 2021 22:25, Anders Jenbo ***@***.***>
escreveu:

**Comment by ZarkTye** [comment]
hey there is how to put buttons on devillutionx


Em seg, 14 de jun de 2021 21:48, Anders Jenbo ***@***.***>
escreveu:

**Comment by AJenbo** [comment]
We are still working on a virtual gamepad, ones that is done we will do a proper release.

**Comment by ZarkTye** [comment]
ok you make this emulator and your project will continue good luck


Em qua, 16 de jun de 2021 18:32, Anders Jenbo ***@***.***>
escreveu:

**Comment by ZarkTye** [comment]
I have one last thing to say when you put touchscreen buttons could you
send me the apk

Em seg, 14 de jun de 2021 21:48, Anders Jenbo ***@***.***>
escreveu:

**Comment by AJenbo** [comment]
It's not an emulator but a native port.

Set your account to watch for new releases:
https://github.com/diasurgical/devilutionX

**Comment by ZarkTye** [comment]
how am i going to mount the apk on android i don't have a pc


Em qui, 17 de jun de 2021 04:51, Anders Jenbo ***@***.***>
escreveu:

**Comment by AJenbo** [comment]
You don't mount APK files, just download and install, a PC is not required for that.

**Comment by ZarkTye** [comment]
and how do i download when i update


Em qui, 17 de jun de 2021 12:44, Anders Jenbo ***@***.***>
escreveu:

**Comment by AJenbo** [comment]
Your questions do not make sens. I suggest looking up a guide on how to install applications on Android.

**Comment by ZarkTye** [comment]
I meant where on your link page do I install the apk when I update I
know how to update


Em qui, 17 de jun de 2021 13:06, Anders Jenbo ***@***.***>
escreveu:

**Comment by AJenbo** [comment]
I don't understand what you are trying to say. This is what you have to click to get notifications of new releases, in case that is what you are asking:
![image](https://user-images.githubusercontent.com/204594/122450371-388a2e00-cfa7-11eb-987b-09fcdbc6d590.png)

**Comment by ZarkTye** [comment]
I <https://dictionary.cambridge.org/pt/dicionario/ingles-portugues/i>
 managed to
<https://dictionary.cambridge.org/pt/dicionario/ingles-portugues/to> run
<https://dictionary.cambridge.org/pt/dicionario/ingles-portugues/run>
 diablo in
<https://dictionary.cambridge.org/pt/dicionario/ingles-portugues/in> firefox


Em qui, 17 de jun de 2021 15:05, Anders Jenbo ***@***.***>
escreveu:

**Comment by ZarkTye** [comment]
I managed to run diablo in firefox click to see 
![Screenshot_20210617-152746](https://user-images.githubusercontent.com/81594191/122455339-aa9c4c00-cf82-11eb-9bb3-3f31c95742f4.png)

**Comment by AJenbo** [comment]
There is now a version for Android which should provide a much better experience: https://play.google.com/store/apps/details?id=org.diasurgical.devilutionx

**Comment by ZarkTye** [comment]
![Screenshot_20211031-111114](https://user-images.githubusercontent.com/81594191/139587754-4f263065-e4e9-43c1-aadd-e1e6a17a5ca5.png)
Ready It's already installed

**Comment by ZarkTye** [comment]
![Uploading Screenshot_20211031-114231.png…]()
Nice Work!

**Comment by ZarkTye** [comment]
![Screenshot_20211031-114231](https://user-images.githubusercontent.com/81594191/139589055-e6382ce8-889f-46f4-8a45-5a323775fc12.png)

Nice Work 👌
