### ISSUE TITLE
Gives me this error when trying to go back to town after loading save.

### ISSUE THREAD

**Issue by jhall39** [d07RiV/diabloweb#42]
[spawn0.zip](https://github.com/d07RiV/diabloweb/files/3464571/spawn0.zip)

**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.14 (Shareware)

**Error message:**
    
    Unable to open save file

**User agent:**

    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by d07RiV** [comment]
Another case of broken save file, still not sure where it's coming from. I'll close it to keep everything in one place since there's already a long discussion in #14.
