### ISSUE TITLE
Following error occured

### ISSUE THREAD

**Issue by dzwiedz90** [d07RiV/diabloweb#44]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.12 (Shareware)

**Error message:**
    
    Unable to open save file

**Comment by d07RiV** [comment]
Were you going back to town? Seems like another issue related to #14 so I'm going to close it to keep things in one place.

**Comment by dzwiedz90** [comment]
Yes. Back to town

niedz., 4.08.2019, 15:59 użytkownik d07RiV <notifications@github.com>
napisał:
