### ISSUE TITLE
Users get confused by the upstream URL in Start menu

### ISSUE THREAD

**Issue by sskras** [d07RiV/diabloweb#45]
So they reports bugs to the upstream a lot:
https://github.com/diasurgical/devilution/issues?utf8=%E2%9C%93&q=is%3Aissue+d07RiV

I think you need to put project's own URL in the first, most visible place. And maybe hide the upstream URL as a one-word link somewhere below. So the choosing priority is more clear:)

**Comment by d07RiV** [comment]
Oh, sorry. I removed the diasurgical link, those that need can find it in links in my README.
