### ISSUE TITLE
jeison

### ISSUE THREAD

**Issue by jpr0419** [d07RiV/diabloweb#455]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Shareware)

**Error message:**
    
    Network Error
        at e.exports (../node_modules/axios/lib/core/createError.js:17:0)
        at createError (../node_modules/axios/lib/adapters/xhr.js:80:0)

**User agent:**

    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
[Please describe what you were doing before the error occurred]
