### ISSUE TITLE
Jah

### ISSUE THREAD

**Issue by bence20** [d07RiV/diabloweb#46]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.17 (Shareware)

**Error message:**
    
    Unable to open save file

**User agent:**

    Mozilla/5.0 (Linux; Android 8.0.0; LDN-L21) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.143 Mobile Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by d07RiV** [comment]
Ith Ber?

I assume it's another corrupted save file issue like in #14 so I'm going to close this to keep everything in one place.
