### ISSUE TITLE
Sound does not play natively on MacOS or IPadOS 15.

### ISSUE THREAD

**Issue by PowerThroughLove** [d07RiV/diabloweb#473]
With Apples latest change to auto play sound fails to load for the game. On Mac you can disable the blocking of auto play for the particular website, however iOS/iPadOS does not allow this, so there is simply no sound for them.

**Comment by AJenbo** [comment]
Afaik there is nothing that can be done done about this. Use devilutionX for Mac, and build a it in xcodr for iPad and
