### ISSUE TITLE
Maybe the WASM files should be compiled from devilutionX project which is based on SDL2

### ISSUE THREAD

**Issue by ZaDarkSide** [d07RiV/diabloweb#48]
In order to sort out the dependencies issues better, maybe it will be best to compile the WASM files from the https://github.com/diasurgical/devilutionX/ project which has support for SDL2 and Emscripten supports SDL2.

**Comment by d07RiV** [comment]
It would need a rewrite either way, since JS needs a centralized event loop, and that project still has lots of modal dialogs and other states like the original game. And I prefer having more control over how things are connected to JS.

**Comment by ZaDarkSide** [comment]
The guys from devilutionX project are fine with supporting Emscripten in the future as a target platform, it's a lot of work but it can be done.

https://github.com/diasurgical/devilutionX/issues/218

**Comment by d07RiV** [comment]
Well I already made mine so it would be too much of a hassle.

Besides, from what I understand, SDL support is mainly aimed at producing a complete HTML page with all the glue code, so adding any additional JS-side functionality (such as touch support) would be difficult.

**Comment by OrangBuangan** [comment]
I think devilutionx is already working on touch support.

**Comment by d07RiV** [comment]
I'm going to close this, as devilutionX seems far away from being able to compile to emscripten, and I like the way I have set it up right now. The main drawback is broken network code, which I may or may not fix in the future.
