### ISSUE TITLE
the hell

### ISSUE THREAD

**Issue by catpat3** [d07RiV/diabloweb#486]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Retail)

**Error message:**
    
    NotReadableError: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.

**User agent:**

    Mozilla/5.0 (X11; CrOS x86_64 13982.88.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.162 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
Try the native Linux client instead https://github.com/diasurgical/devilutionX/releases
