### ISSUE TITLE
???

### ISSUE THREAD

**Issue by arekkola1** [d07RiV/diabloweb#49]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.17 (Retail)

**Error message:**
    
    Main program archive: diabdat.mpq

**User agent:**

    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by d07RiV** [comment]
Seems you didn't select a proper DIABDAT.MPQ.
