### ISSUE TITLE
Question: Save Location

### ISSUE THREAD

**Issue by Hiethen** [d07RiV/diabloweb#50]
What is the save location of diabloweb? Thanks

**Comment by OrangBuangan** [comment]
They are saved in browser memory, use DownloadSaves() in console to get them.

**Comment by d07RiV** [comment]
It's using browser's IndexedDB storage, you won't find them on your disk.

As @OrangBuangan mentioned, I added a couple functions for downloading the files, they're currently only available from JS console (available through F12), but I will add UI for managing saves later on.

**Comment by gwmccull** [comment]
@d07RiV if I download the save file, is there a way to move the file to a new computer? Getting a new laptop soon and I don't want to lose my game 😢 

Are there instructions for this? I would be happy to contribute to docs if not

**Comment by OrangBuangan** [comment]
@gwmccull I think you can drag and drop the save file on the game just like the MPQ and then it will load it.

**Comment by ChaosMarc** [comment]
yes, @OrangBuangan is correct. You can upload you save game files (though not multiple at once) by dragging them on the screen where you can upload your diabdat.mpq / start shareware. 

I'm not sure if it's necessary to add this fact to the documentation as @d07RiV mentioned he wants to implement a UI for the export as well as the import of save games.

**Comment by d07RiV** [comment]
I'm still looking to add network support, so I'll try to make a proper UI once that is done.
