### ISSUE TITLE
error: abort("Assertion failed: no binaryen method succeeded.")

### ISSUE THREAD

**Issue by BenjamienSD** [d07RiV/diabloweb#51]
**Description:**
	Clicked "Play Shareware", downloading bar appears, completes, then error message is shown.

**App version:**
	DiabloWeb 1.0.18 (Shareware)

**Browser**
	Firefox Developer Edition 69.0b10 (64-bit)
	(no issues on Chrome or Firefox with fresh profile)

**Error message:**

	e/</</<@https://d07riv.github.io/diabloweb/static/js/main.af57bee7.chunk.js:1:4291
   
*on screen*

	 The following error has occurred:
	 abort("Assertion failed: no binaryen method succeeded."). Build with -s ASSERTIONS=1 for more info.

*console warnings/errors*

```
SecurityError: The operation is insecure. 0.24a15045.chunk.js:1
	9		https://diablo.rivsoft.net/static/js/0.24a15045.chunk.js:1
	f		https://diablo.rivsoft.net/storage.html:1
	8		https://diablo.rivsoft.net/static/js/storage.97895d82.chunk.js:1
	f		https://diablo.rivsoft.net/storage.html:1
	57		https://diablo.rivsoft.net/static/js/storage.97895d82.chunk.js:1
	f		https://diablo.rivsoft.net/storage.html:1
	a		https://diablo.rivsoft.net/storage.html:1
	e		https://diablo.rivsoft.net/storage.html:1
	<anonymous>	https://diablo.rivsoft.net/static/js/storage.97895d82.chunk.js:1

no native wasm support detected 	bafab200b9781958d643.worker.js:1:42157
Assertion failed: no binaryen method succeeded.	bafab200b9781958d643.worker.js:1:60312

Source map error: ReferenceError: WebAssembly is not defined
Resource URL: https://d07riv.github.io/diabloweb/static/css/main.e49ccae7.chunk.css
Source Map URL: main.e49ccae7.chunk.css.map

Source map error: ReferenceError: WebAssembly is not defined
Resource URL: https://diablo.rivsoft.net/static/js/0.24a15045.chunk.js
Source Map URL: 0.24a15045.chunk.js.map

Source map error: ReferenceError: WebAssembly is not defined
Resource URL: https://diablo.rivsoft.net/static/js/storage.97895d82.chunk.js
Source Map URL: storage.97895d82.chunk.js.map
```

**User agent:**
	
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0

**Save file:**

	n/a

**note**

Issue is almost certainly related to security/privacy settings in user.js of user profile.
Quick and dirty workaround is to go to about:profiles, select Profile: troubleshoot -> Launch profile in new browser. Not sure how I would go about finding out which user setting is responsible though.

**Comment by d07RiV** [comment]
I think WebAssembly might be disabled by default or something? Not sure why they're still doing it.

**Comment by BenjamienSD** [comment]
Brilliant. 
about:config -> javascript.options.wasm -> set to true
works like a charm.


It's set to true by default, I must've messed with it at some point.
Thank you!
