### ISSUE TITLE
errror message what do I do? 

### ISSUE THREAD

**Issue by Rickodesandi** [d07RiV/diabloweb#53]
**Description:**
I purchased D1 and tried to open the file, then I recieved following error message, The following error has occurred:

invalid MPQ file at: Source/rmpq/archive.cpp line 30

Click to create an issue on GitHub
*App version:**
DiabloWeb 1.0.18 (Shareware)

**Error message:**
    
    invalid MPQ file
    at: Source/rmpq/archive.cpp line 30

**User agent:**

    Mozilla/5.0 (Linux; Android 9; CLT-L09) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.89 Mobile Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by Rickodesandi** [comment]
Just to add the D1 is in downloads folder which I choose to open with the link, however error pops up.

**Comment by d07RiV** [comment]
Seems you're trying to opening the wrong file. Which one are you selecting?

**Comment by Rickodesandi** [comment]
Seams like I need software to open this file?

GOG Galaxy Diablo_Helfire.exe

**Comment by OrangBuangan** [comment]
@Rickodesandi you need to extract diabdat.mpq and give it that file. You can either install it first on your PC or follow this guide: https://github.com/diasurgical/devilutionX/wiki/Extracting-the-DIABDAT.MPQ-from-the-GoG-installer

**Comment by Rickodesandi** [comment]
Thanks
Well... I am on android device so probably need a software to open the
folder and access files. Any idea what can I use to do it?

**Comment by OrangBuangan** [comment]
Sorry I think you will need Windows or Linux to extract the file

**Comment by Rickodesandi** [comment]
Ok I see... I will look into this later today. Thanks
