### ISSUE TITLE
Item bug - 'Sword of bashing

### ISSUE THREAD

**Issue by diablogithub** [d07RiV/diabloweb#532]
![bug](https://user-images.githubusercontent.com/104338439/165018644-3421e8ab-8347-48d7-bcc7-2c9e0475969f.png)

**Comment by diablogithub** [comment]
Using the warrior, finished Nightmare mode and started a new game in Hell mode. This new unique item randomly appeared in my inventory when I talked to the NPCs in the town. 

I suspect it got mixed up with the Butcher's dropped item.

This new game: no wounded townsman at the cathedral's entrance. That means no Butcher's quest.

**Comment by AJenbo** [comment]
This is a bug in the original game, it is caused by item flags not being cleared properly. If you want a fixed version of the game you can use DevilutionX: https://github.com/diasurgical/devilutionX#readme
