### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by mooncircle** [d07RiV/diabloweb#54]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.18 (Shareware)

**Error message:**
    
    Error: Network Error
        at e.exports (https://d07riv.github.io/diabloweb/static/js/5.473ccc28.chunk.js:1:20793)
        at XMLHttpRequest.d.onerror (https://d07riv.github.io/diabloweb/static/js/5.473ccc28.chunk.js:1:19836)

**User agent:**

    Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by d07RiV** [comment]
Sounds like a network error (aka failed to download something). Does it happen every time? If not, just try again, nothing unusual.
