### ISSUE TITLE
Demo is not working.

### ISSUE THREAD

**Issue by nsicko42** [d07RiV/diabloweb#541]
**Description:**
that's all with message below

The following error has occurred:

ReferenceError: WebAssembly is not defined

Click to create an issue on GitHub

**App version:**
DiabloWeb 1.0.39 (Shareware)

**Error message:**
    
    ReferenceError: WebAssembly is not defined
        at https://d07riv.github.io/diabloweb/d2271be9a67638d3642f.worker.js?__WB_REVISION__=4115803155f6ffac29dc0498aae8c82f:1:38580
        at https://d07riv.github.io/diabloweb/d2271be9a67638d3642f.worker.js?__WB_REVISION__=4115803155f6ffac29dc0498aae8c82f:1:78234
        at call (../node_modules/regenerator-runtime/runtime.js:45:0)
        at tryCatch (../node_modules/regenerator-runtime/runtime.js:264:0)
        at _invoke (../node_modules/regenerator-runtime/runtime.js:98:0)
        at arg (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:0)
        at asyncGeneratorStep (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:0)

**User agent:**

    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
Are you using the official site or did you load it from somewhere else?

**Comment by nsicko42** [comment]
> Are you using the official site or did you load it from somewhere else?

i am using https://d07riv.github.io/diabloweb/
I was clicked "Play Shareware".

Maybe this isn't the official site?

**Comment by AJenbo** [comment]
That is indeed the official one, but I'm unable to replicate the issue both when trying in Firefox and Chrome/103.0.5060.134 (slightly newer then what you reported)

**Comment by nsicko42** [comment]
> That is indeed the official one, but I'm unable to replicate the issue both when trying in Firefox and Chrome/103.0.5060.134 (slightly newer then what you reported)

Could it be a problem if the browser is edge?

I just updated my browser and clear that the browser agent is "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 Edg/103.0.1264.71".

But the problem is still there.

**Comment by AJenbo** [comment]
Just installed Edge (103.0.1264.71) and that also appears to work just fine:

![image](https://user-images.githubusercontent.com/204594/180608106-39477b67-aec5-4e91-b893-34197bddd3f2.png)

My only other suggestion is to use [DevilutionX](https://github.com/diasurgical/devilutionX#readme) instead. It's not web based, but supports most platforms natively. It's also backwards compatible with the original shareware where diabloweb has a few bugs that breaks things.
