### ISSUE TITLE
Inclusion into ScummVM?

### ISSUE THREAD

**Issue by rubyFeedback** [d07RiV/diabloweb#544]
Hey there,

Any of you thought of including it into ScummVM?

Kind of as a first step for ScummVM to also focus on:

a) the www

and

b) legacy games?

At any rate this is just a suggestion or question. Don't worry about it too much
and feel free to close this issue at any moment in time.

**Comment by AJenbo** [comment]
There are several reasons that wouldn't happen. If you want a native port to other platforms try DeviultionX
