### ISSUE TITLE
Unable to Download Shareware

### ISSUE THREAD

**Issue by abenelazar** [d07RiV/diabloweb#55]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.19 (Shareware)

**Error message:**
    
    Error: Request failed with status code 404
        at createError (http://localhost:3000/static/js/0.chunk.js:728:15)
        at settle (http://localhost:3000/static/js/0.chunk.js:944:12)
        at XMLHttpRequest.handleLoad (http://localhost:3000/static/js/0.chunk.js:251:7)

**User agent:**

    Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by d07RiV** [comment]
That's odd, not sure if I'm hitting some limits or if github pages is having issues. Are you getting it very time? I got a broken page once, but tried again and it loaded just fine.
