### ISSUE TITLE
Lost my save when switched to .mpq

### ISSUE THREAD

**Issue by Eddeg6969420** [d07RiV/diabloweb#550]
I was playing Diablo in shareware mode and I came to level three of the dungeon and it wasn’t available in shareware so I decide to download the .mpq from my friend. But I wanted to continue on my game save but I couldn’t. What should I do?

**Comment by AJenbo** [comment]
Shareware saves are not compatible with the full version

**Comment by Eddeg6969420** [comment]
Can you make them compatible?

Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Anders Jenbo ***@***.***>
Skickat: Monday, February 13, 2023 1:40:06 PM
Till: d07RiV/diabloweb ***@***.***>
Kopia: Edvin Gjerdrum (elev) ***@***.***>; Author ***@***.***>
Ämne: Re: [d07RiV/diabloweb] Lost my save when switched to .mpq (Issue #550)


Closed #550<https://github.com/d07RiV/diabloweb/issues/550> as completed.

**Comment by AJenbo** [comment]
no, diabloweb also has bugs in it's shareware version that makes to incompatible with the original

**Comment by Eddeg6969420** [comment]
Pls

Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Anders Jenbo ***@***.***>
Skickat: Monday, February 13, 2023 1:42:43 PM
Till: d07RiV/diabloweb ***@***.***>
Kopia: Edvin Gjerdrum (elev) ***@***.***>; Author ***@***.***>
Ämne: Re: [d07RiV/diabloweb] Lost my save when switched to .mpq (Issue #550)


no, diabloweb also has bugs in it's shareware version that makes to incompatible with the original
