### ISSUE TITLE
Esign

### ISSUE THREAD

**Issue by Ben165469** [d07RiV/diabloweb#559]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Shareware)

**Error message:**
    
    Network Error
        at (unknown) (https://d07riv.github.io/diabloweb/static/js/5.430d8c5c.chunk.js:1:119017)
        at (unknown) (https://d07riv.github.io/diabloweb/static/js/5.430d8c5c.chunk.js:1:118052)

**User agent:**

    Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
[Please describe what you were doing before the error occurred]
 
 Since you are on a Mac maybe it would make sens for you to use [DevilutionX](https://github.com/diasurgical/devilutionX/releases/latest) which has native support.
