### ISSUE TITLE
Can I support the development?

### ISSUE THREAD

**Issue by ackvf** [d07RiV/diabloweb#56]
Hi, do you have a Patreon so that we can support the development?

I would love to see the multiplayer!

**Comment by d07RiV** [comment]
Not a fan of patreon since it would feel more like a job than a hobby. I'll probably try to sneak in some ads when I rework the landing page.

**Comment by ackvf** [comment]
The way I see and use Patreon is as a way to thank the creators for their effort and free time they put in, not as a community employment, but I understand that the more patreons, the more you could feel obliged.

**Comment by nilemarbarcelos** [comment]
Hi, how about the new sponsors feature?
https://github.com/sponsors

**Comment by ackvf** [comment]
But for github sponsors the owner of the repo must apply first, right? I can't find the button.

**Comment by AJenbo** [comment]
Thanks for the interest and support, but the Diasurgical would like to keep the Devilution project free of the influence of money. Instead we take Pull Requests, word of mouth and testers :)
