### ISSUE TITLE
HOW TO HOST IN A PERSONAL SERVER

### ISSUE THREAD

**Issue by blazeBR** [d07RiV/diabloweb#561]
I'm trying to play this online with my friends, but can't connect anyway. How can I put this into a personal server? I'm a newbie in this things, but I think I can make it works.

**Comment by AJenbo** [comment]
> How can I put this into a personal server?

It's not clear what you expect from doing so, it's not going to enable you to play multiplayer. At best it would allow you to access it without an internet connection or run a mod.
