### ISSUE TITLE
t

### ISSUE THREAD

**Issue by ghost** [d07RiV/diabloweb#564]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Shareware)

**Error message:**
    
    Network Error
        at https://playclassic.games/wp-content/uploads/single-games/diabloweb/static/js/5.5e5d7b53.chunk.js?__WB_REVISION__=d9258a7f6f137b231338:1:119306
        at createError (../node_modules/axios/lib/adapters/xhr.js:85:0)

**User agent:**

    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
[Please describe what you were doing before the error occurred]
 
 Tip, don't play it on an unofficial site.
