### ISSUE TITLE
Eu sou al o niversau

### ISSUE THREAD

**Issue by Flaviotrind** [d07RiV/diabloweb#568]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Retail)

**Error message:**
    
    NotReadableError: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.

**User agent:**

    Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by Flaviotrind** [comment]
Tá fora

**Comment by AJenbo** [comment]
Use DevilutionX on Android
