### ISSUE TITLE
It's unclear what NodeJS version is needed to compile this

### ISSUE THREAD

**Issue by grepwood** [d07RiV/diabloweb#570]
I couldn't find any such info, or maybe I didn't look good enough :(

**Comment by AJenbo** [comment]
NPM 7.20.0 was the latest at the time, feel free to update the docs if you find something more specific.
NodeJS was something like 15.14.

**Comment by grepwood** [comment]
Thanks! I've managed to compile it with v14.21.3. Any system will do, so long as it's got `python2`, `git` and `make` in `${PATH}` as well.

**Comment by AJenbo** [comment]
On a side note devilutionX is both natively supported on Linux (and bsd) and can be build for webasm, though we are looking for someone to tie together the last few bits.

**Comment by grepwood** [comment]
@AJenbo I know about DevilutionX. I remember many years ago I tried to involve myself in the big endian port, but life commitments have taken over. I'll try and get in touch on Discord soon.

**Comment by AJenbo** [comment]
Yeah I thought I recognized your avatar but could not find the reference in your history.

If you are still interested in BigEndian we still have an outstanding issue in terms of being able to play multiplayer between little and big endian systems.

Edit: Oh found it; https://github.com/diasurgical/devilutionX/issues/71

**Comment by grepwood** [comment]
> Yeah I thought I recognized your avatar but could not find the reference in your history.
> 
> If you are still interested in BigEndian we still have an outstanding issue in terms of being able to play multiplayer between little and big endian systems.
> 
> Edit: Oh found it; [diasurgical/devilutionX#71](https://github.com/diasurgical/devilutionX/issues/71)

We couldn't have found a better time to run into each other. It just so happens I have a Mac G5 with 16GB RAM, SSD, and Gentoo on it, so I can do these tests much more efficiently than on a humble PS3 :)

**Comment by AJenbo** [comment]
Sounds great :)

**Comment by sskras** [comment]
@grepwood commented [1 hour ago](https://github.com/d07RiV/diabloweb/issues/570#issuecomment-2102009635):

> We couldn't have found a better time to run into each other. It just so happens I have a Mac G5 with 16GB RAM, SSD, and Gentoo on it, so I can do these tests much more efficiently than on a humble PS3 :)

If you start working on a fix, I am going to suggest @AdelieLinux folks to package it. This distro loves Power Macs :)

**Comment by AJenbo** [comment]
the game dose already run though, so no reasen for them not to realy
