### ISSUE TITLE
Loading a game saved from the shareware version into the full version

### ISSUE THREAD

**Issue by AllanCentuple100x** [d07RiV/diabloweb#573]
When I first found this game I was so excited about playing it, I forgot to load the MPQ into it and just started playing with the shareware version, until I got to the point of not being able to enter Level 3 of the dungeon. 

I saved the game, downloaded the file to desktop, loaded in my MPQ, but can't find a way to load it and continue from where I last was. What's wrong?

**Comment by AJenbo** [comment]
- Diabloweb produces shareware saves that are incompatible with the original
- Shareware saves cannot be converted in to full retail version

Also please note that you cannot convert between single player and multi player save games.
