### ISSUE TITLE
Error reducing mpq size

### ISSUE THREAD

**Issue by GregScorp** [d07RiV/diabloweb#574]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Shareware)

**Error message:**
    
    RangeError: WebAssembly.Memory(): could not allocate memory
        at https://playclassic.games/wp-content/uploads/single-games/diabloweb/8b39eb9dcd801767796e.worker.js?__WB_REVISION__=9f448c8a22b6eff732fb0751cf949d8d:1:7717
        at https://playclassic.games/wp-content/uploads/single-games/diabloweb/8b39eb9dcd801767796e.worker.js?__WB_REVISION__=9f448c8a22b6eff732fb0751cf949d8d:1:30708
        at c (../node_modules/regenerator-runtime/runtime.js:49:0)
        at Generator._invoke (../node_modules/regenerator-runtime/runtime.js:271:0)
        at t.<computed> (../node_modules/regenerator-runtime/runtime.js:167:0)
        at a (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:7:0)
        at err (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:28:0)
        at https://playclassic.games/wp-content/uploads/single-games/diabloweb/8b39eb9dcd801767796e.worker.js?__WB_REVISION__=9f448c8a22b6eff732fb0751cf949d8d:1:31141
        at new Promise (<anonymous>)
        at fn (../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:22:0)

**User agent:**

    Mozilla/5.0 (Linux; Android 8.0.0; ASUS_X00QD) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
[Please describe what you were doing before the error occurred]

Best I can tell you ran out of RAM.

Since you have and Android device why not use the native DevilutionX app instead. It supports using audio mp3 as the audio format so you can convert it on your PC if space is an issue on your device.
