### ISSUE TITLE
Can't download Diablo

### ISSUE THREAD

**Issue by MLC603** [d07RiV/diabloweb#578]
**Description:**
[Please describe what you were doing before the error occurred]
I was trying to download the game diablo, its my favorite game and my cousin just told me it was online now... So I couldn't wait and went right to try and play it.....
**App version:**
DiabloWeb 1.0.39 (Shareware)

**Error message:**
    
    Network Error
        at e.exports (https://playclassic.games/wp-content/uploads/single-games/diabloweb/static/js/5.5e5d7b53.chunk.js:1:119306)
        at d.onerror (https://playclassic.games/wp-content/uploads/single-games/diabloweb/static/js/5.5e5d7b53.chunk.js:1:118281)

**User agent:**
![Screenshot_6-8-2024_53051_playclassic games](https://github.com/user-attachments/assets/b4e7f5f4-abdd-496a-8a99-6a789ca79784)

    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
Don't use playclassic.games, we have nothing to do with them and they shows ads which we don't allow.
