### ISSUE TITLE
Compile Error with Chromium Client

### ISSUE THREAD

**Issue by mchartois** [d07RiV/diabloweb#58]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.18 (Shareware)

**Error message:**
    
    Error: CompileError: WebAssembly.compile(): Wasm decoding failedResult = expected version 0d 00 00 00, found 01 00 00 00 @+4
    
        at https://d07riv.github.io/diabloweb/bafab200b9781958d643.worker.js:1:43347
        at Worker.<anonymous> (https://d07riv.github.io/diabloweb/static/js/main.af57bee7.chunk.js:1:4291)

**User agent:**

    Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.2988.0 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by d07RiV** [comment]
Chrome 58? That seems rather old, is there an option to update it?
