### ISSUE TITLE
bliyat

### ISSUE THREAD

**Issue by miroslawas** [d07RiV/diabloweb#581]
**Description:**
[Please+describe+what+you+were+doing+before+the+error+occurred]

**App+version:**
DiabloWeb+1.0.39+(Shareware)

**Error+message:**
++++
++++Database+is+closed
++++++++at+(unknown)+(../node_modules/idb-kv-store/index.js:175:0)
++++++++at+(unknown)+(../node_modules/idb-kv-store/index.js:105:0)
++++++++at+(unknown)+(api/load_spawn.js:32:14)
++++++++at+obj+(../node_modules/regenerator-runtime/runtime.js:45:0)
++++++++at+innerFn+(../node_modules/regenerator-runtime/runtime.js:264:0)
++++++++at+arg+(../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:0)
++++++++at+gen+(../node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:0)

**User+agent:**

++++Mozilla/5.0+(iPhone;+CPU+iPhone+OS+17_5_1+like+Mac+OS+X)+AppleWebKit/605.1.15+(KHTML,+like+Gecko)+Version/17.5+Mobile/15E148+Safari/604.1

**Save+file:**
[Please+attach+the+save+file,+if+applicable.+The+error+box+should+have+a+link+to+download+the+current+save+you+were+playing;+alternatively,+you+can+open+dev+console+on+the+game+page+(F12)+and+type+in+`DownloadSaves()`]

**Comment by AJenbo** [comment]
Go away
