### ISSUE TITLE
Possibility to add patch mpq for latest 1.09b

### ISSUE THREAD

**Issue by michelcouto** [d07RiV/diabloweb#59]
Right now, the game will only use the DIABDAT.MPQ to load. It would be great if we can also provide Patch_rt.mpq as well. This file contains patch informations for the latest avaiable patch, which is 1.09b. It contains some bug fixes.

**Comment by d07RiV** [comment]
That shouldn't be too hard, I'll try. Does the GoG version have it?

**Comment by OrangBuangan** [comment]
Patch_rt.mpq and Patch_sh.mpq (shareware) only contain new battlenet menu graphics, and since diabloweb doesn't have battlenet support it won't change anything.

All changes to the game are in the exe and since devilution is 1:1 with Diablo.exe 1.09b all changes are already in.

**Comment by michelcouto** [comment]
I see. I thought that the possibility to duplicate items were removed in later patches.
Also, when killing diablo the game is simply restarting, without showing the cutscene (and that I think was also a problem in later versions of diablo, prior to patching).

**Comment by OrangBuangan** [comment]
No dubbing is still possible in the latest versions of the game.

Videos work correctly in devilution, but this is a known issue with diabloweb.

**Comment by d07RiV** [comment]
Yes, I finally got to Diablo on my phone last night, and noticed the missing cutscene. I pushed a change that I thought would fix it, but apparently that wasn't enough.

**Comment by d07RiV** [comment]
Okay fixed videos, now I need to rework my state queuing system because it's a mess.

**Comment by michelcouto** [comment]
Cool, thanks! Guess this one can be closed then, since as @OrangBuangan  said, it is not needed to support the patch mpq.
