### ISSUE TITLE
Вот

### ISSUE THREAD

**Issue by mohctep65** [d07RiV/diabloweb#591]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Shareware)

**Error message:**
    
    Request aborted
        at e.exports (../node_modules/axios/lib/core/createError.js:17:0)
        at createError (../node_modules/axios/lib/adapters/xhr.js:71:0)

**User agent:**

    Mozilla/5.0 (Linux; arm_64; Android 14; ALI-NX1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.48 YaBrowser/24.9.0.48.00 SA/3 Mobile Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
[Please describe what you were doing before the error occurred]

You are on Android, use DevilutionX instad
