### ISSUE TITLE
DiabloWeb 1.0.39 (Shareware)

### ISSUE THREAD

**Issue by Andrelew-1956** [d07RiV/diabloweb#595]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.39 (Shareware)

**Error message:**
    
    Request failed with status code 400
        at e.exports (../node_modules/axios/lib/core/createError.js:17:0)
        at createError (../node_modules/axios/lib/core/settle.js:19:0)
        at resolve (../node_modules/axios/lib/adapters/xhr.js:60:0)
    

**User agent:**

    Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
[Please describe what you were doing before the error occurred]
