### ISSUE TITLE
Game bugs out entering King Leoric's Tomb (Shareware)

### ISSUE THREAD

**Issue by RHOPKINS13** [d07RiV/diabloweb#6]
Save file attached. When entering King Leoric's Tomb, it gets stuck on the level loading screen, and the progress indicator flashes erratically.

[spawn0.zip](https://github.com/d07RiV/diabloweb/files/3458952/spawn0.zip)

**Comment by d07RiV** [comment]
You're not actually meant to reach level 3 in shareware, I will be updating it soon to show a proper message after level 2.

**Comment by d07RiV** [comment]
Shareware should now prevent you from going past level 2
