### ISSUE TITLE
Please allow difficult selector for Single Player

### ISSUE THREAD

**Issue by michelcouto** [d07RiV/diabloweb#60]
It doesn't need to actually work, but when we have a multiplayer character, then we can use a hack to enable Nightmare and Hell mode for single player characters:

-Start a multi player game of Nightmare or Hell difficulty (character must be of sufficient level to start game) 
-Select new game from menu 
-Cancel back to single player selection 
-Start a new game or load a saved single player game 
-The single player game is now playing as if you had set the difficulty equivalent to the last multi player game 
-The difficulty does not save with the character so this must be done each time you play

**Comment by d07RiV** [comment]
I'm working on proper multiplayer, can't say when it would be ready though.

I'm not sure if the trick would even work that way, since I completely rewrote the menus. Might as well make an explicit difficulty selector at that rate.

**Comment by michelcouto** [comment]
That would be great to have that supported in single player as well!
Otherwise, the game is not cool enough to be played after killing diablo.

**Comment by michelcouto** [comment]
Should I rename this to:
Please allow difficult selector for Single Player?

**Comment by d07RiV** [comment]
Did it work correctly, with no bugs in single player? I think it would be a pretty cool idea, letting players choose difficulty when creating a new game once you've killed Diablo.

**Comment by michelcouto** [comment]
I've encountered no bugs in single player, except the one I told you before, and it was fixed, regarding the cutscene after killing Diablo.

I also think it would be really cool to let the user select the dificulty, the same ones available in multiplayer (Nightmare once the player is level 20 or above, and Hell once the player is level 30 or above).

**Comment by OrangBuangan** [comment]
The only issue is that it isn't saved to the game so you have to pick difficulty each time you load the game.

**Comment by michelcouto** [comment]
Well, better than not having it at all :-)

**Comment by d07RiV** [comment]
I can make it save difficulty, at the cost of nightmare/hell saves not being valid in other versions of the game.

I'm trying to make it allow selecting difficulty based on highest completed difficulty, like in D2, and it's not working out too well because the game isn't saved after you kill Diablo (aka in single player your highest completed difficulty is always 0). I tried forcing a save before playing cinematics and if you load the save you appear stuck watching Diablo death animation.. not sure if I can actually do that.

Should I just let people load any difficulty they want from the get go (like multiplayer)?

**Comment by OrangBuangan** [comment]
Players can't start/join a difficulty level in multiplayer unless they are the required level or higher (20 and 30).

Normally you can save the game while Diablo is bleeding and when load and the game continue correctly, so this might be a bug in webdiablo.

**Comment by d07RiV** [comment]
I can save while diablo is bleeding, then when I load I can move again but it is kinda glitchy (it will teleport me around a bit) and the cutscene plays anyway. I was referring to saving after the actual diablo death event, just before cinematic plays, which results in me loading to a bugged state.

I like the level 20/30 idea, I'll use that I suppose.

**Comment by d07RiV** [comment]
Added in 1.0.23

**Comment by michelcouto** [comment]
I am back from a short vacation. Tks for implementing that.
What did you end up doing for the save?
Did you save the difficulty level (so the save is not valid in other versions of the game)?

**Comment by ChaosMarc** [comment]
> Did you save the difficulty level (so the save is not valid in other versions of the game)?

He did just that :( that's a no go for me. One of the coolest things of diabloweb was that I could move the saves from and to my local installation without any hickups. 

All solutions which implement this for the desktop installation (like [DiabloPatch](https://diablopat.ch/) offer the difficulty selection every time, which is completely fine in my books.

**Comment by michelcouto** [comment]
Well, either that, or perhaps 2 different files could be saved. One containing the difficulty, and the other one not.
This way, he could use the difficulty if it is present, or don't.
Anyway, I also agree that perhaps not saving the difficult level, and letting the user select it every time would be better.

**Comment by AJenbo** [comment]
There is lots of unused space in the save game where extra info like this could be saved and still stay comfortable. That's how we plan to handle it for devilutionX

**Comment by d07RiV** [comment]
@ChaosMarc 
I use a different "signature" ID for save files to indicate difficulty level. If you want to port the save to other versions of the game, you can always re-start it in normal and save again.

**Comment by michelcouto** [comment]
Hi. Something must be broken. I see that gold drop by killing monsters equivales to Nightmare when I play, but I am getting 0xp for killing a monster. So I think there is some kind of bug going on.
