### ISSUE TITLE
Speech audio keeps playing after closing the dialogue

### ISSUE THREAD

**Issue by jtsiomb** [d07RiV/diabloweb#61]
When you talk to a character, or trigger any other kind of speech item, in the original game the audio would stop as soon as you exited that dialogue. In this version it keeps playing, and if you start a second dialogue option both speech audio files play at the same time, making the result incoherent.

**Comment by d07RiV** [comment]
I remember making sure it works when I first made it, maybe a recent audio update broke it, I'll check again.

**Comment by d07RiV** [comment]
Fixed in 1.0.23
