### ISSUE TITLE
Talking about Butcher forever

### ISSUE THREAD

**Issue by AlexDVasilkov** [d07RiV/diabloweb#62]
The villagers only have Gossip and The Butcher talking options, regardless of quest completion. I know, I know, who ever talks to the NPCs? Well I do.

**Comment by d07RiV** [comment]
I have a fix but I can't deploy it right now since there's a lot of other changes I'm not finished with.

**Comment by OrangBuangan** [comment]
@d07RiV is this related to https://github.com/diasurgical/devilutionX/issues/223

**Comment by d07RiV** [comment]
Fixed in 1.0.23

**Comment by d07RiV** [comment]
@OrangBuangan no, it was a bug in how I determine audio duration after I removed audio decoding from the code and let browser API do that for me.
