### ISSUE TITLE
Help just paid to play full version

### ISSUE THREAD

**Issue by mikee91az** [d07RiV/diabloweb#63]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.24 (Shareware)

**Error message:**
    
    invalid MPQ file
    at: Source/rmpq/archive.cpp line 30

**User agent:**

    Mozilla/5.0 (Linux; Android 9; SM-G973U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.89 Mobile Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by mikee91az** [comment]
The following error has occurred:

invalid MPQ file at: Source/rmpq/archive.cpp line 30

Click to create an issue on GitHub

**Comment by OrangBuangan** [comment]
Make sure that you select diabdat.mpq and not the installation

**Comment by mikee91az** [comment]
I can't get an app to open the exe to look for the  diabdat.mpq. I'm using my s10 . I have no PC access

**Comment by OrangBuangan** [comment]
Without access to a PC it will be pretty hard to get the data file.

1: One thing you can try is installing a virtual pc with linux on your device and then follow the guide for extracting it https://github.com/diasurgical/devilutionX/wiki/Extracting-the-DIABDAT.MPQ-from-the-GoG-installer

2: Maybe write to GOG support and ask if they can help you.

3: Borrow a PC, maybe at an internet cafe

**Comment by d07RiV** [comment]
@OrangBuangan do you think it's possible to extract the MPQ from installer? I know old blizzard installers were technically MPQ archives. Or is it a network installer now?

**Comment by OrangBuangan** [comment]
If you compile innoextract yes, afaik they use some compression so you can't just cut it out of the file.

The old Blizzard installer didn't contain the diabdat.mpq, it was just on the cd. The shareware installer had the mpq in an mpq in the exe, it would probably have needed PKware to uncompress.

**Comment by domdorn** [comment]
.. have you tried googling for diabdat.mpq ...
