### ISSUE TITLE
Crash While loading diabdat. Mpq

### ISSUE THREAD

**Issue by Razzzor1911** [d07RiV/diabloweb#66]
There is a such issue only on loading big mpq file, While playing shareware all is going great!
I tried on Samsung note 4, 3 gb RAM. Can it be an insufficient of memory? Is there is a way to fix it?

**Comment by d07RiV** [comment]
What do you mean by crash? Does the browser page crash, or does the site show some error message in a red box?

**Comment by Razzzor1911** [comment]
Chrome, Opera and Samsung browser just shows error loading page , and firefox shows some page with code. 
Of course, tried to shut down all others apps, but no effect

**Comment by d07RiV** [comment]
Error loading page? You mean you can't even choose the MPQ?

Not sure what to suggest here. The browser version supports a more compact form of MPQ with MP3 audio instead of WAV but the tool I use to make those is not in a state that can be shared atm.

**Comment by AJenbo** [comment]
The MPQ compression has been released, please try this and report back if there are still issues.
