### ISSUE TITLE
When going down to level 13. It crashes with RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by MANassar** [d07RiV/diabloweb#69]
**Description:**
Going down to level 13.

`RangeError: Maximum call stack size exceeded.`
![C2C9D99B-D994-464A-8D3A-DBD1284DB876](https://user-images.githubusercontent.com/1597951/62984441-7f4ef000-be33-11e9-88c7-829fdca3cc66.png)

**App version:**
DiabloWeb 1.0.28 (Retail)

**Error message:**
    
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]
    <?>.wasm-function[290]@[wasm code]

**User agent:**

    Mozilla/5.0 (iPad; CPU OS 13_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/18.1b15719 Mobile/15E148 Safari/605.1.15

**Save file:**

I’m unable to attach the save file because I could not download it from the iPad. 

[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by d07RiV** [comment]
Does the "download save" link not work on iPad, either? It's hard to tell what's going on without it :(

**Comment by MANassar** [comment]
I understand of course. The “download save” link does look like a link, but its not tappable as one. I can even download the page where one creates the new Github issue. (Check attachment), but cant download the save

Can you try making the error screen show a full text link to the save? That way I can copy paste it and try to download it.
![29DB3A81-9F08-4768-947C-87352542EE59](https://user-images.githubusercontent.com/1597951/63135535-96761500-bfce-11e9-837d-af63362cb2fb.png)
![39B5783B-E73D-4396-BB26-DF6C7A3CD224](https://user-images.githubusercontent.com/1597951/63135704-156b4d80-bfcf-11e9-92b6-420c068371f6.png)

**Comment by d07RiV** [comment]
It's not a real link since the file is stored in memory. I changed it to be an actual link with blob URL, hopefully it will work for you now. (Version 1.0.35)

**Comment by MANassar** [comment]
Thanks. Here’s the save file
[8b086493-54b4-4f5f-90ce-151b6bb11a62.zip](https://github.com/d07RiV/diabloweb/files/3523112/8b086493-54b4-4f5f-90ce-151b6bb11a62.zip) af

**Comment by MANassar** [comment]
The URI to create an issue is too long so it fails with 414. Here it is anyway

https://github.com/d07RiV/diabloweb/issues/new?body=**Description%3A**%0A%5BPlease+describe+what+you+were+doing+before+the+error+occurred%5D%0A%0A**App+version%3A**%0ADiabloWeb+1.0.35+%28Retail%29%0A%0A**Error+message%3A**%0A++++%0A++++RangeError%3A+Maximum+call+stack+size+exceeded.%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A++++%3C%3F%3E.wasm-function%5B__Z11DRLG_L4FTVRiiiii%5D%40%5Bwasm+code%5D%0A%0A**User+agent%3A**%0A%0A++++Mozilla%2F5.0+%28iPad%3B+CPU+OS+13_0+like+Mac+OS+X%29+AppleWebKit%2F605.1.15+%28KHTML%2C+like+Gecko%29+FxiOS%2F18.1b15719+Mobile%2F15E148+Safari%2F605.1.15%0A%0A**Save+file%3A**%0A%5BPlease+attach+the+save+file%2C+if+applicable.+The+error+box+should+have+a+link+to+download+the+current+save+you+were+playing%3B+alternatively%2C+you+can+open+dev+console+on+the+game+page+%28F12%29+and+type+in+%60DownloadSaves%28%29%60%5D%0A

**Comment by Forbes256** [comment]
Same issue. Same level. I don't understand how to fix.

Loving playing D1 again, THANK YOU!

**Comment by AJenbo** [comment]
This is most likely OOB errors, most of these are fixed in DevilutionX, you can find the iOS branch here: https://github.com/diasurgical/devilutionX/pull/182
