### ISSUE TITLE
memory acces out of bounds

### ISSUE THREAD

**Issue by maxswift01** [d07RiV/diabloweb#7]
when exiting the first dungeon I receive the subject error

**Comment by d07RiV** [comment]
Is it consistent? Could you attach the savefile so I can try to reproduce it?

You can export savefiles by opening console (F12) and typing `DownloadSaves()`.

**Comment by hiramhibbard** [comment]
Just had the same issue when exiting the first dungeon.

**Comment by maxswift01** [comment]
seems to be only when i boot from mpq, not from the share.

**Comment by maxswift01** [comment]
is there a similar osx function? not familiar, I'm sorry

**Comment by maxswift01** [comment]
when going to level 2 on the first dungeon, i am presented with only a dark screen. see attached. 
![Screen Shot 2019-08-01 at 8 51 06 PM](https://user-images.githubusercontent.com/53585738/62336412-2a5bc300-b49e-11e9-9367-d0fc18105360.png)

**Comment by d07RiV** [comment]
Going down to level 2 should no longer crash, if it still does please send save files.
