### ISSUE TITLE
No change in Version Nr.

### ISSUE THREAD

**Issue by Hellvortex** [d07RiV/diabloweb#71]
Hey there, I saw that you wrote the Version should be 1.27, but I'm still getting only the .26.
Is that how it should be or do I have to do anything?

**Comment by d07RiV** [comment]
I'm using a service worker to cache the site for offline use, the side effect is that it won't load the new version until you close all tabs with the site.

**Comment by Hellvortex** [comment]
Aaaah, perfect, now it changed to 1.0.29

Thx a lot for the great work man!
