### ISSUE TITLE
Diablo

### ISSUE THREAD

**Issue by MekkyCZ** [d07RiV/diabloweb#72]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.30 (Shareware)

**Error message:**
    
    invalid MPQ file
    at: Source/rmpq/archive.cpp line 30

**User agent:**

    Mozilla/5.0 (Linux; Android 9; Lenovo TB-X705F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.89 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by OrangBuangan** [comment]
Make sure you select diabdat.mpq and not another file like the installer exe.

**Comment by d07RiV** [comment]
Think it's about time I make it check file name.

**Comment by ChaosMarc** [comment]
and perhaps a meaningful error page explaining in detail where to get the game and how to extract the diabdat.mpq

**Comment by d07RiV** [comment]
I added an error message if user tries to upload something other than MPQ (and SV) files, with a bit of information. It's not pretty (a standard alert window), I'll update the front page to be more useful some time later.
