### ISSUE TITLE
what now?

### ISSUE THREAD

**Issue by D1v1s0r** [d07RiV/diabloweb#73]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.30 (Shareware)

**Error message:**
    
    Unable to open save file

**User agent:**

    Mozilla/5.0 (Linux; Android 5.0.1; K007) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.89 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by d07RiV** [comment]
Can you attach the save file?

**Comment by AJenbo** [comment]
There is now a version for Android fixes a few issues that could have resulted in this situation: https://play.google.com/store/apps/details?id=org.diasurgical.devilutionx
