### ISSUE TITLE
Shareware multiplayer crashed upon two restarts in a row

### ISSUE THREAD

**Issue by sskras** [d07RiV/diabloweb#77]
**Description:**
I was playing multiplayer game of Shareware version in WebSocket (Server) mode. Then I decided to create a new game. After new game was created (actually two times in a row), I moved to the Blacksmith.  I saw that the gamma was reset (the picture got darker) and decided to correct this. I pressed `Esc` to go to menu. I forgot if I pressed `Options` or not then. 

But something lagged in the current tab IIRC, and promptly some error screen was presented to me:

![image](https://user-images.githubusercontent.com/7887758/63216029-bc6af900-c137-11e9-8975-4c50117f53dc.png)

**App version:**
DiabloWeb 1.0.33 (Shareware)

**Error message:**
    
        at audioBatch (api/game.worker.js:306:8)
        at func (api/game.worker.js:282:4)
        at try_api (api/game.worker.js:289:2)
        at apply (api/game.worker.js:410:12)
    

**User agent:**

    Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0

**Save file:**
I pressed `DownloadSaves()` but it produced three files (instead of one which I expected). Maybe that's because I had run a new tab with the game afterwards (just to check sequence on my actions).  

Attaching all three in a .zip :
[2019-08-17__sskras_DiabloWeb_1.0.33_Shareware_multiplayer_crash_save_files.zip](https://github.com/d07RiV/diabloweb/files/3512342/2019-08-17__sskras_DiabloWeb_1.0.33_Shareware_multiplayer_crash_save_files.zip)

**Comment by sskras** [comment]
[2019-08-17__sskras_DiabloWeb_1.0.33_Shareware_multiplayer_crash_save_files.zip](https://github.com/d07RiV/diabloweb/files/3512344/2019-08-17__sskras_DiabloWeb_1.0.33_Shareware_multiplayer_crash_save_files.zip)

**Comment by d07RiV** [comment]
DownloadSaves will give a file for every character, that's normal.

I think I found the problem, should be fixed in 1.0.34. The error message is slightly different for me but I guess that's Firefox vs Chrome.

**Comment by sskras** [comment]
Thanks for taking a look. 

BTW, it seems I do not receive notifications about commits in this repo (for some reason). Although I have switched on `[ Watching ]` (Be notified of all conversations). Do you have any ideas why?

**Comment by d07RiV** [comment]
No idea, I'm getting notified of all conversations but not commits, I thought that's the norm?

**Comment by AJenbo** [comment]
you should also get them for PRs
