### ISSUE TITLE
Ending cutscene not running, not (properly) starting New Game +

### ISSUE THREAD

**Issue by knickum** [d07RiV/diabloweb#78]
After I beat Diablo, the endgame cutscene doesn't run, and upon starting New Game, the dungeons don't seem to regenerate properly.

If I select my existing character (which is fine -- all the equipment/money I had) from the menu, then select New Game, I start back in Tristram and I can get all new quests (e.g., I didn't have the Butcher quest before, but the body is lying there to start the Butcher quest, gets added to the Quest dialog).

When I enter the dungeon, the map is sort of half-explored (but not entirely, there are some unrevealed areas), some doors are opened, but any closed doors can't be opened, and all enemies are dead. The dungeon map is different each time, but the same conditions.

I tried to go down to the lower levels to see what happens -- maybe it's just the first four, but because some doors don't open, it's possible that there's no path to the level exit (this happened the first and only time I've tried so far).

As far as I've seen, there are no displayed or JS errors.

**Comment by knickum** [comment]
I should add -- saw this note, which seems to be a similar problem: https://www.reddit.com/r/Diablo/comments/9w85za/i_killed_the_diablo_in_diablo_1_but/

It seems in that person's case, using the original Diablo installed as normal, they needed to update to 1.09b to fix the issue.

**Comment by d07RiV** [comment]
I had that bug before where it doesn't properly clear the saved levels, maybe I accidentally brought it back when I was fiddling with the menus.

Not sure why the ending wouldn't run, though.

**Comment by knickum** [comment]
AGH! That's on me, I generated the build, and am running it on my own server. Just pulled new code, ran 'npm run build' and started a New Game and it looks like the dungeon generated fine (at least, I could open a door and there were enemies walking around).
