### ISSUE TITLE
OOM running on Android + Firefox

### ISSUE THREAD

**Issue by lemellofonseca** [d07RiV/diabloweb#81]
**Description:**
[Please describe what you were doing before the error occurred]

**App version:**
DiabloWeb 1.0.36 (Retail)

**Error message:**
    
    [Exception... "Out of Memory"  nsresult: "0x8007000e (NS_ERROR_OUT_OF_MEMORY)"  location: "JS frame :: https://d07riv.github.io/diabloweb/8f2900d82a26cf7fccd2.worker.js?__WB_REVISION__=b8ad87ef610d14c8e17a5c7715dd91d2 :: Y/< :: line 1"  data: no]

**User agent:**

    Mozilla/5.0 (Android 8.1.0; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
How much ram does your device have, and how much did it have available?

**Comment by d07RiV** [comment]
I'll try to make a tool for compacting the MPQ so that the game uses less resources, since it seems to be a common issue. Hopefully it would help in these cases.

**Comment by lemellofonseca** [comment]
It's a Motorola G5 Plus, which should be 2GB

Running Memoryinfo & Swapcheck app, it shows 611 free ram of 1,80 GB

Seems to be the culprit. Any idea of what can be done to free more ram memory?

**Comment by d07RiV** [comment]
I just added an option to compress your MPQ file, it can produce a much smaller (~250MB) MPQ out of the retail one, which should run better on phones. Click the link on the main page, select your MPQ and wait for the page to process it (better do it on PC because it can be quite slow).

**Comment by lemellofonseca** [comment]
Perfect! I can now play my good old Diablo 😍

**Comment by AJenbo** [comment]
There also now a version for Android which uses significantly less memory: https://play.google.com/store/apps/details?id=org.diasurgical.devilutionx
