### ISSUE TITLE
Failure to create a WebSocket (Server) multiplayer game

### ISSUE THREAD

**Issue by sskras** [d07RiV/diabloweb#82]
If I go menu > Multi Player > WebSocket (Server), it waits for ~1s and then just throws this message:

> Connection timed out

![image](https://user-images.githubusercontent.com/7887758/63637196-7e635d00-c682-11e9-8372-16f5bdec3f6c.png)

**Comment by sskras** [comment]
In Chrome(OS) console appears this:

`WebSocket connection to 'wss://diablo.rivsoft.net/websocket' failed: Error during WebSocket handshake: Unexpected response code: 503`

Console log saved: [d07riv.github.io-1566649164890.log](https://github.com/d07RiV/diabloweb/files/3537173/d07riv.github.io-1566649164890.log)

**Comment by d07RiV** [comment]
Ah yes I took down the servers (both websocket and RTC) temporarily because my other site was overloaded and server was having issues. I upgraded to a new server but I haven't finished moving everything there yet.

**Comment by sskras** [comment]
Thanks. And now it works again.
Is there any HowTo about setting up own WebSocket server for diabloweb?
