### ISSUE TITLE
the following error has accured: main program archive spawn.mpq

### ISSUE THREAD

**Issue by govital** [d07RiV/diabloweb#87]
**Description:**
pressed select mpq and selected my mpq file from the diablo i purchessed on GOG
[DRTL_IX86_108_109.mpq.zip](https://github.com/d07RiV/diabloweb/files/3565247/DRTL_IX86_108_109.mpq.zip)

**App version:**
DiabloWeb 1.0.22 (Shareware)

**Error message:**
    
    Main program archive: spawn.mpq

**User agent:**

    Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

**Save file:**
[Please attach the save file, if applicable. The error box should have a link to download the current save you were playing; alternatively, you can open dev console on the game page (F12) and type in `DownloadSaves()`]

**Comment by AJenbo** [comment]
The mpq you have attached is the patch for updating the original diablo 1.08 to 1.09.
You have to select the diabdat.mpq to play the full game. It should be about 500 mb in size.

**Comment by govital** [comment]
Thank you! it worked! So happy now!
