### ISSUE TITLE
Hell difficulty greyed out

### ISSUE THREAD

**Issue by mrt123** [d07RiV/diabloweb#88]
As per title, "Hell" is greyed out, while normal and nightmare works ok (this is for multiplayer, my character is lvl30).

I was trying to find a valid reason why game itself would prevent me to do this, but didn't come across anything. Forgive me if this is not an actual bug.

**Comment by ChaosMarc** [comment]
Is your character above level 30? This is a requirement to start MP games in hell difficulty.

**Comment by mrt123** [comment]
@ChaosMarc yes I'm exactly lvl30 on that character, I don't have other characters on multiplayer

**Comment by mrt123** [comment]
Turned out I needed to be lvl 31 :P

**Comment by ChaosMarc** [comment]
@d07RiV I would suggest you take a look at that level check. IIRC you manually implemented that. maybe there is a >= vs. > or 0-based vs. 1-based mixup
