### ISSUE TITLE
drawing api question

### ISSUE THREAD

**Issue by nbarkhina** [d07RiV/diabloweb#9]
Hey i'm just super curious about how you ported it for emscripten. I've been trying to learn it and my C++ is quite rusty. This weekend will try to compile it myself. Can you explain how you're actually drawing to the html canvas? I think you rewrote the drawing functions in dx.cpp I see - #ifdef EMSCRIPTEN 

EM_JS( void, api_draw_blit, (int x, int y, int w, int h, void* ptr), {
  self.DApi.draw_blit(x, y, w, h, HEAPU8.subarray(ptr, ptr + w * h * 4));
});

my question is what is DApi? i don't see that anywhere in your source code. is that an emscripten function? or an SDL drawing function?

Thanks

**Comment by d07RiV** [comment]
Those are functions defined in Javascript (worker.js). I am using a global object with all the functions so they're in one place.

**Comment by nbarkhina** [comment]
ah I see now that's in the React project. Thanks!
