### ISSUE TITLE
Resource to view active multiplayer games

### ISSUE THREAD

**Issue by mrt123** [d07RiV/diabloweb#93]
Hi, Do you expose any resource to query what games are currently open on the server (game name + difficulty , maybe time open) ?

BTW: Could I develop a simple tool (Web UI) to view active games if one doesn't exist yet ?

**Comment by d07RiV** [comment]
I'd rather make an in-game view, the API is there I just never got around to making a menu for it.

**Comment by mrt123** [comment]
I'd be happy to create a PR with that extra menu item and list of games underneath. 

I'd only need the api paths required to get the games data. Ideally a list of :  /game name/ game level / time since opened / optionally list of players or player count.
I presume you'd want a top level link in your React app, to keep the Diablo itself vanilla. Upon entering will be simple list of games for now. 

Respond to my email if you're interested.
